name: Environment Variable

on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
      - "*.md"
      - "!*.txt"
env:
  WORKFLOW_VAR: 'WORKFLOW VARIABLE'
    
jobs:
  job-1:
    name: 1st job
    runs-on: ubuntu-24.04
    env:
      JOB_VAR: 'JOB'
    steps:
      - name: Step 1
        env:
          STEP_VAR: 'STEP'
        run: |
          console.log(`WorkflowVariable= ${process.env.WORKFLOW_VAR}`)
          console.log(`STEP_VAR= ${process.env.STEP_VAR}`)
          console.log(`JOB_VAR= ${process.env.JOB_VAR}`)
        shell: node {0}
      - name: Step 2
        run: |
          echo "WorkflowVariable= $WORKFLOW_VAR"
          echo "STEP_VAR= $STEP_VAR"
          echo "JOB_VAR= $JOB_VAR"

  job-2:
    runs-on: ubuntu-24.04
    steps:
      - name: Step 3
        run: |
          import os
          
          print(f"WorkflowVariable= {os.getenv('WORKFLOW_VAR')}")
          print(f"STEP_VAR= {os.getenv('STEP_VAR')}")
          print(f"JOB_VAR= {os.getenv('JOB_VAR')}")
        shell: python